brain_two/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('todos/', (include('todos.urls', 'todos'))),

]

todos/urls.py
from django.urls import path
from . import views

app_name = "todos"

urlpatterns = [
    path("", views.todo_list, name="todo_list_list"),
    path('create/', views.todo_list_create, name='todo_list_create'),
    path('<int:id>/', views.todo_list_detail, name='todo_list_detail'),
    path('<int:id>/edit/', views.todo_list_update, name='todo_list_update'),
    path('<int:id>/delete/', views.todo_list_delete, name='todo_list_delete'),
    path('items/create/', views.todo_item_create, name='todo_item_create'),
    path('items/<int:id>/edit/', views.todo_item_update, name='todo_item_update'),

]

todos/models.py
from django.db import models

class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        'TodoList',
        related_name="items",
        on_delete=models.CASCADE
    )

todos/forms.py
from django import forms
from .models import TodoList
from .models import TodoItem
class TodoListForm(forms.ModelForm):
    class Meta:
        model = TodoList
        fields = ['name']

class TodoItemForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ['task', 'due_date', 'is_completed']

todos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import TodoList
from .forms import TodoListForm
from .forms import TodoItemForm

def todo_list_detail(request, id):
    todo_list = get_object_or_404(TodoList, pk=id)
    return render(request, 'todos/todo_detail.html', {'todo_list': todo_list})

def todo_list(request):
    todo_lists = TodoList.objects.all()
    return render(request, 'todos/todo_list.html', {'todo_lists': todo_lists})
def todo_list_update(request, id):
    todo_list = get_object_or_404(TodoList, pk=id)

    if request.method == 'POST':
        form = TodoListForm(request.POST, instance=todo_list)
        if form.is_valid():
            form.save()
            return redirect('todos:todo_list_detail', id=id)

    else:
        form = TodoListForm(instance=todo_list)

    return render(request, 'todos/todo_update.html', {'form': form})

def todo_list_create(request):
    if request.method == 'POST':
        form = TodoListForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('todos:todo_list_detail', id=form.instance.id)
    else:
        form = TodoListForm()

    return render(request, 'todos/todo_create.html', {'form': form})

def todo_list_delete(request, id):
    todo_list = get_object_or_404(TodoList, pk=id)

    if request.method == 'POST':
        todo_list.delete()
        return redirect('todos:todo_list_list')  # Redirect to the list view after deletion

    return render(request, 'todos/todo_delete.html', {'todo_list': todo_list})

def todo_item_create(request, list_id=None):
    todo_list = None

    if list_id is not None:
        todo_list = get_object_or_404(TodoList, pk=list_id)

        if request.method == 'POST':
            form = TodoItemForm(request.POST)
            if form.is_valid():
                # Create a new to-do item associated with the to-do list
                item = form.save(commit=False)
                if todo_list is not None:
                    item.list = todo_list
                item.save()
                return redirect('todos:todo_list_detail', id=list_id)

    else:
        form = TodoItemForm()

    return render(request, 'todos/todo_item_create.html', {'form': form, 'todo_list': todo_list, 'list_id': list_id})

def todo_item_update(request, id):
    todo_item = get_object_or_404(TodoItem, pk=id)

    if request.method == 'POST':
        form = TodoItemForm(request.POST, instance=todo_item)
        if form.is_valid():
            form.save()
            return redirect('todos:todo_list_detail', id=todo_item.list.id)
    else:
        form = TodoItemForm(instance=todo_item)

    return render(request, 'todos/todo_item_update.html', {'form': form, 'todo_item': todo_item})

todos/templates/todos/todo_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create a New List</title>
</head>
<body>
    <main>
        <div>
            <h1>Create a new list</h1>
            <form method="post">
                {% csrf_token %} {# Include a CSRF token for security #}
                <input type="text" name="name">
                <button>Create</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/todo_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Todo List</title>
</head>
<body>
    <main>
        <div>
            <h1>Are you sure?</h1>
            <form method="post">
                {% csrf_token %}
                <button type="submit">Delete</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/todo_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo List Detail</title>
</head>
<body>
    <main>
        <div>
            <h1>{{ todo_list.name }}</h1>
            <a href="{% url 'todos:todo_list_update' todo_list.id %}">Edit</a>
            <a href="{% url 'todos:todo_list_delete' todo_list.id %}">Delete</a>

            <h2>Tasks</h2>
            <table>
                <thead>
                    <tr>
                        <th>Task</th>
                        <th>Due date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in todo_list.items.all %}
                    <tr>
                        <td>{{ task.task }}</td>
                        <td>{{ task.due_date }}</td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="2">No tasks available for this list.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>

todos/templates/todos/todo_item_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create New Todo Item</title>
</head>
<body>
    <main>
        <div>
            <h1>Create a new item</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="hidden" name="list" value="{{ todo_list.id }}">
                <button type="submit">Create</button>
            </form>
        </div>
    </main>
</body>
</html>

todos/templates/todos/todo_item_update.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div>
            <h1>Update item</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update</button>
            </form>
        </div>
    </main>
{% endblock %}

todos/templates/todos/todo_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Todo Lists</title>
</head>
<body>
    <main>
        <div>
            <h1>My Lists</h1>
            <div>
                <a href="{% url 'todos:todo_item_create' %}">Create a new item</a> <!-- New link to create a new item -->
            </div>
            <div>
                <a href="{% url 'todos:todo_list_create' %}">Create a new list</a>
            </div>
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of items</th>
                        <th>Edit</th>
                    </tr>
                </thead>
                <tbody>
                    {% for todo_list in todo_lists %}
                    <tr>
                        <td><a href="{% url 'todos:todo_list_detail' todo_list.id %}">{{ todo_list.name }}</a></td>
                        <td>{{ todo_list.items.count }}</td>
                        <td><a href="{% url 'todos:todo_list_update' todo_list.id %}">Edit</a></td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="3">No to-do lists available.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </main>
</body>
</html>

todos/templates/todos/todo_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update Todo List</title>
</head>
<body>
    <main>
        <div>
            <h1>Update List</h1>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Update</button>
            </form>
        </div>
    </main>
</body>
</html>